name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0         # full history for Jekyll-free deploy
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: .       # ルート直下の HTML/CSS/img をそのまま公開
      - name: Deploy
        uses: actions/deploy-pages@v1
